### PR TITLE
[school-test] Add tests for schools

### PR DESCRIPTION
**Pull request by falkecarlsen**
Tests whether generated school placement is within some distance of real school placement by assigning each point (school) in both sets to each other while minimising distance. This is the assignment problem.

Note that unmatched schools are not considered, meaning that if a city has four schools, but only one is generated, only the one pair is used. This likely leads to artificially better results.

```
Testing school placement on following cities: Esbjerg, Slagelse, Randers, Vejen, Aalborg
Null hypothesis: Generated schools are placed worse than 1500 meters away from real schools
Alt. hypothesis: Generated schools are placed exactly or better than 1500 meters away from real schools
School placement test of Esbjerg:
	All schools placed better than bound: False
	Mean divergence: 846.69 meters
	T-test with bound 1500 meters. T-stat: -4.75604, p-value: 0.00038
	Since t-stat is zero or negative, and p-value is of statistical significance (p <= 0.05), the null-hypothesis can be rejected.
School placement test of Slagelse:
	All schools placed better than bound: True
	Mean divergence: 579.09 meters
	T-test with bound 1500 meters. T-stat: -7.43063, p-value: 0.00031
	Since t-stat is zero or negative, and p-value is of statistical significance (p <= 0.05), the null-hypothesis can be rejected.
School placement test of Randers:
	All schools placed better than bound: True
	Mean divergence: 668.44 meters
	T-test with bound 1500 meters. T-stat: -5.57979, p-value: 0.00083
	Since t-stat is zero or negative, and p-value is of statistical significance (p <= 0.05), the null-hypothesis can be rejected.
School placement test of Vejen:
	All schools placed better than bound: True
	Mean divergence: 522.59 meters
	[WARN] Cannot make a t-test on a single divergence
	However, the divergence (522.59 meters) is less or equal than 1500
School placement test of Aalborg:
	All schools placed better than bound: False
	Mean divergence: 929.44 meters
	T-test with bound 1500 meters. T-stat: -4.63966, p-value: 0.00027
	Since t-stat is zero or negative, and p-value is of statistical significance (p <= 0.05), the null-hypothesis can be rejected.
```

### CODE REVIEW

**Comment by falkecarlsen** [comment]
Also produces pretty images of the city with generated and real schools, and their respective assignments.

Note that this plotting is quite expensive (~5 mins for the five cities). Profiling shows that the vast majority of time is spent by `sumolib`, so this is likely not an easy optimisation nor is is very important.

image
image
image
image
image

**Review by NicEastvillage — APPROVED** [review]

**Review by MathiasMehl — APPROVED** [review]

**Comment by NicEastvillage** [comment]
Hold on. `scipy.stat.ttest_1samp` is a two-sided test and thus checks if `A == B`.
https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.ttest_1samp.html

Divide p-val by 2 and check if t-stat is negative. Only then can we reject `A < B`. Optionally see:
https://stackoverflow.com/questions/44947229/one-sided-one-sample-t-test-python

Luckily, this will only make our p-val lower, so the null-hypothesis can be even more rejected :P

**Review by NicEastvillage — CHANGES_REQUESTED** [review]
See comment above.

**Comment by falkecarlsen** [comment]
> See comment above.

Fixed in ab08242. Now bound is 1150m and statistically significant for all cities.

**Review by NicEastvillage — APPROVED** [review]
That's an oddly chosen bound. One would almost believe you chose it *after* running the test if a few times :P

**Pull request merged**
