### PR TITLE
[Cleanup] Refactor and reordering

### PR DESCRIPTION
**Pull request by falkecarlsen**
- Remove `statistics.py`
- Remove experimental render functions
- Move `verify_stats` and `setup_city_gates` to `utility.py`
- Clean up `display_network`s arguments, docstrings, and unused variables and imported functions
- Abstract logging setup into `utility.py`

Discussed with @MathiasMehl on abstracting all school-oriented functions into a `school.py` file. This needs args to be passed as arguments, unfortunately. This should be fixed in #27.

### CODE REVIEW

**Comment by NicEastvillage** [comment]
Good initiative!

> Move `setup_city_gates` to utility.py

I disagree on this. It is a functionality and not a helper/utility function, so it should either be in `randomActivityGen.py` or `gates.py`. And tbh, I don't mind if we have both gates and schools in `randomActivityGen.py` even though it gets a bit long.

**Review by NicEastvillage — CHANGES_REQUESTED** [review]
I have looked through the changes now. And my only objective is the comment above.

**Review by jenrik — COMMENTED** [review]
Things seems to have been move around correctly :+1:

**Comment by MathiasMehl** [comment]
I agree that `setup_city_gates` should not be in utility.py. Otherwise looks cool

**Comment by falkecarlsen** [comment]
Moved `setup_city_gates` into `gates.py` in fb4e519. 
It is the only function in the file but I'd rather have `randomActivityGen.py` be clean.

**Review by NicEastvillage — APPROVED** [review]

**Pull request merged**
