### PR TITLE
[docs] Document the entire codebase

### PR DESCRIPTION
**Pull request by jenrik**
- [x] bus.py
- [x] gates.py
- [x] perlin.py
- [x] randomActivityGen.py
- [x] render.py
- [x] school.py
- [x] testCityGates.py
- [x] testSchools.py
- [x] tripsToCSV.py
- [x] utility.py

### CODE REVIEW

**Comment by falkecarlsen** [comment]
#65 adds docstrings to `testSchools.py` so I would consider that finished when merged

**Comment by NicEastvillage** [comment]
Looks like we are done.

**Comment by falkecarlsen** [comment]
Still needs README elaborations. I'm working on it.

**Review by falkecarlsen — APPROVED** [review]
Good for now

**Pull request merged**
